# Generated by Django 4.1.5 on 2023-02-01 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter your Name', max_length=254, verbose_name='Name')),
                ('last_name', models.CharField(help_text='Enter your Surname', max_length=254, verbose_name='Surname')),
                ('email', models.EmailField(help_text='Enter your email', max_length=254, unique=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name', 'email'],
            },
        ),
    ]
