# Generated by Django 4.1.5 on 2023-02-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='(The date and time when Log was created.)', verbose_name='Created Time')),
                ('path', models.URLField(help_text='The PATH of the Request.', max_length=199, verbose_name='The PATH')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('HEAD', 'HEAD'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('CONNECT', 'CONNECT'), ('OPTIONS', 'OPTIONS'), ('TRACE', 'TRACE'), ('PATCH', 'PATCH')], help_text='A method (GET, POST, others).', max_length=7, verbose_name='The Method')),
                ('request_data', models.JSONField(null=True, verbose_name='Request data in JSON')),
                ('run_time', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Execution time of the request.')),
            ],
            options={
                'ordering': ['timestamp', 'path', 'method'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="(e.g. 'Anna' or 'Anna-Claire')", max_length=254, verbose_name='Name')),
                ('last_name', models.CharField(help_text="(e.g. 'Stopford' or 'Stopford-Sackville')", max_length=254, verbose_name='Surname')),
                ('email', models.EmailField(help_text='(A valid email address, please.)', max_length=254, unique=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name', 'email'],
            },
        ),
    ]
